<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->deleteAllRows();
        $countries = $this->defineData();
        $this->insertAllData($countries);
    }
    private function deleteAllRows()
    {
        Schema::withoutForeignKeyConstraints(function () {
            Country::truncate();
        });
    }
    private function insertAllData($data)
    {
        foreach ($data as $key => $value) {
            Country::create($value);
        }
    }
    private function defineData()
    {
        return [
            ['name' => 'Afghanistan', 'official_state_name' => 'The Islamic Republic of Afghanistan', 'code' => 'AF'],
            ['name' => 'Åland Islands', 'official_state_name' => 'Åland', 'code' => 'AX'],
            ['name' => 'Albania', 'official_state_name' => 'The Republic of Albania', 'code' => 'AL'],
            ['name' => 'Algeria', 'official_state_name' => 'The People\'s Democratic Republic of Algeria', 'code' => 'DZ'],
            ['name' => 'American Samoa', 'official_state_name' => 'The Territory of American Samoa', 'code' => 'AS'],
            ['name' => 'Andorra', 'official_state_name' => 'The Principality of Andorra', 'code' => 'AD'],
            ['name' => 'Angola', 'official_state_name' => 'The Republic of Angola', 'code' => 'AO'],
            ['name' => 'Anguilla', 'official_state_name' => 'Anguilla', 'code' => 'AI'],
            ['name' => 'Antarctica', 'official_state_name' => 'All land and ice shelves south of the 60th parallel south', 'code' => 'AQ'],
            ['name' => 'Antigua and Barbuda', 'official_state_name' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['name' => 'Argentina', 'official_state_name' => 'The Argentine Republic', 'code' => 'AR'],
            ['name' => 'Armenia', 'official_state_name' => 'The Republic of Armenia', 'code' => 'AM'],
            ['name' => 'Aruba', 'official_state_name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Australia', 'official_state_name' => 'The Commonwealth of Australia', 'code' => 'AU'],
            ['name' => 'Austria', 'official_state_name' => 'The Republic of Austria', 'code' => 'AT'],
            ['name' => 'Azerbaijan', 'official_state_name' => 'The Republic of Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Bahamas', 'official_state_name' => 'The Commonwealth of The Bahamas', 'code' => 'BS'],
            ['name' => 'Bahrain', 'official_state_name' => 'The Kingdom of Bahrain', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'official_state_name' => 'The People\'s Republic of Bangladesh', 'code' => 'BD'],
            ['name' => 'Barbados', 'official_state_name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belarus', 'official_state_name' => 'The Republic of Belarus', 'code' => 'BY'],
            ['name' => 'Belgium', 'official_state_name' => 'The Kingdom of Belgium', 'code' => 'BE'],
            ['name' => 'Belize', 'official_state_name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Benin', 'official_state_name' => 'The Republic of Benin', 'code' => 'BJ'],
            ['name' => 'Bermuda', 'official_state_name' => 'Bermuda', 'code' => 'BM'],
            ['name' => 'Bhutan', 'official_state_name' => 'The Kingdom of Bhutan', 'code' => 'BT'],
            ['name' => 'Bolivia', 'official_state_name' => 'The Plurinational State of Bolivia', 'code' => 'BO'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'official_state_name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ'],
            ['name' => 'Bosnia and Herzegovina', 'official_state_name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'Botswana', 'official_state_name' => 'The Republic of Botswana', 'code' => 'BW'],
            ['name' => 'Bouvet Island', 'official_state_name' => 'Bouvet Island', 'code' => 'BV'],
            ['name' => 'Brazil', 'official_state_name' => 'The Federative Republic of Brazil', 'code' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'official_state_name' => 'The British Indian Ocean Territory', 'code' => 'IO'],
            ['name' => 'Brunei Darussalam', 'official_state_name' => 'The Nation of Brunei, the Abode of Peace', 'code' => 'BN'],
            ['name' => 'Bulgaria', 'official_state_name' => 'The Republic of Bulgaria', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'official_state_name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundi', 'official_state_name' => 'The Republic of Burundi', 'code' => 'BI'],
            ['name' => 'Cabo Verde', 'official_state_name' => 'The Republic of Cabo Verde', 'code' => 'CV'],
            ['name' => 'Cambodia', 'official_state_name' => 'The Kingdom of Cambodia', 'code' => 'KH'],
            ['name' => 'Cameroon', 'official_state_name' => 'The Republic of Cameroon', 'code' => 'CM'],
            ['name' => 'Canada', 'official_state_name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Cayman Islands', 'official_state_name' => 'The Cayman Islands', 'code' => 'KY'],
            ['name' => 'Central African Republic', 'official_state_name' => 'The Central African Republic', 'code' => 'CF'],
            ['name' => 'Chad', 'official_state_name' => 'The Republic of Chad', 'code' => 'TD'],
            ['name' => 'Chile', 'official_state_name' => 'The Republic of Chile', 'code' => 'CL'],
            ['name' => 'China', 'official_state_name' => 'The People\'s Republic of China', 'code' => 'CN'],
            ['name' => 'Christmas Island', 'official_state_name' => 'The Territory of Christmas Island', 'code' => 'CX'],
            ['name' => 'Cocos (Keeling) Islands', 'official_state_name' => 'The Territory of Cocos (Keeling) Islands', 'code' => 'CC'],
            ['name' => 'Colombia', 'official_state_name' => 'The Republic of Colombia', 'code' => 'CO'],
            ['name' => 'Comoros', 'official_state_name' => 'The Union of the Comoros', 'code' => 'KM'],
            ['name' => 'Congo', 'official_state_name' => 'The Republic of the Congo', 'code' => 'CG'],
            ['name' => 'DR Congo', 'official_state_name' => 'The Democratic Republic of the Congo', 'code' => 'CD'],
            ['name' => 'Cook Islands', 'official_state_name' => 'The Cook Islands', 'code' => 'CK'],
            ['name' => 'Costa Rica', 'official_state_name' => 'The Republic of Costa Rica', 'code' => 'CR'],
            ['name' => 'Côte d\'Ivoire', 'official_state_name' => 'The Republic of Côte d\'Ivoire', 'code' => 'CI'],
            ['name' => 'Croatia', 'official_state_name' => 'The Republic of Croatia', 'code' => 'HR'],
            ['name' => 'Cuba', 'official_state_name' => 'The Republic of Cuba', 'code' => 'CU'],
            ['name' => 'Curaçao', 'official_state_name' => 'The Country of Curaçao', 'code' => 'CW'],
            ['name' => 'Cyprus', 'official_state_name' => 'The Republic of Cyprus', 'code' => 'CY'],
            ['name' => 'Czech Republic', 'official_state_name' => 'The Czech Republic', 'code' => 'CZ'],
            ['name' => 'Denmark', 'official_state_name' => 'The Kingdom of Denmark', 'code' => 'DK'],
            ['name' => 'Djibouti', 'official_state_name' => 'The Republic of Djibouti', 'code' => 'DJ'],
            ['name' => 'Dominica', 'official_state_name' => 'The Commonwealth of Dominica', 'code' => 'DM'],
            ['name' => 'Dominican Republic', 'official_state_name' => 'The Dominican Republic', 'code' => 'DO'],
            ['name' => 'Ecuador', 'official_state_name' => 'The Republic of Ecuador', 'code' => 'EC'],
            ['name' => 'Egypt', 'official_state_name' => 'The Arab Republic of Egypt', 'code' => 'EG'],
            ['name' => 'El Salvador', 'official_state_name' => 'The Republic of El Salvador', 'code' => 'SV'],
            ['name' => 'Equatorial Guinea', 'official_state_name' => 'The Republic of Equatorial Guinea', 'code' => 'GQ'],
            ['name' => 'Eritrea', 'official_state_name' => 'The State of Eritrea', 'code' => 'ER'],
            ['name' => 'Estonia', 'official_state_name' => 'The Republic of Estonia', 'code' => 'EE'],
            ['name' => 'Eswatini', 'official_state_name' => 'The Kingdom of Eswatini', 'code' => 'SZ'],
            ['name' => 'Ethiopia', 'official_state_name' => 'The Federal Democratic Republic of Ethiopia', 'code' => 'ET'],
            ['name' => 'Falkland Islands (Malvinas)', 'official_state_name' => 'The Falkland Islands', 'code' => 'FK'],
            ['name' => 'Faroe Islands', 'official_state_name' => 'The Faroe Islands', 'code' => 'FO'],
            ['name' => 'Fiji', 'official_state_name' => 'The Republic of Fiji', 'code' => 'FJ'],
            ['name' => 'Finland', 'official_state_name' => 'The Republic of Finland', 'code' => 'FI'],
            ['name' => 'France', 'official_state_name' => 'The French Republic', 'code' => 'FR'],
            ['name' => 'French Guiana', 'official_state_name' => 'Guyane', 'code' => 'GF'],
            ['name' => 'French Polynesia', 'official_state_name' => 'French Polynesia', 'code' => 'PF'],
            ['name' => 'French Southern Territories', 'official_state_name' => 'The French Southern and Antarctic Lands', 'code' => 'TF'],
            ['name' => 'Gabon', 'official_state_name' => 'The Gabonese Republic', 'code' => 'GA'],
            ['name' => 'Gambia', 'official_state_name' => 'The Republic of The Gambia', 'code' => 'GM'],
            ['name' => 'Georgia', 'official_state_name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Germany', 'official_state_name' => 'The Federal Republic of Germany', 'code' => 'DE'],
            ['name' => 'Ghana', 'official_state_name' => 'The Republic of Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'official_state_name' => 'Gibraltar', 'code' => 'GI'],
            ['name' => 'Greece', 'official_state_name' => 'The Hellenic Republic', 'code' => 'GR'],
            ['name' => 'Greenland', 'official_state_name' => 'Kalaallit Nunaat', 'code' => 'GL'],
            ['name' => 'Grenada', 'official_state_name' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'official_state_name' => 'Guadeloupe', 'code' => 'GP'],
            ['name' => 'Guam', 'official_state_name' => 'The Territory of Guam', 'code' => 'GU'],
            ['name' => 'Guatemala', 'official_state_name' => 'The Republic of Guatemala', 'code' => 'GT'],
            ['name' => 'Guernsey', 'official_state_name' => 'The Bailiwick of Guernsey', 'code' => 'GG'],
            ['name' => 'Guinea', 'official_state_name' => 'The Republic of Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'official_state_name' => 'The Republic of Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Guyana', 'official_state_name' => 'The Co-operative Republic of Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'official_state_name' => 'The Republic of Haiti', 'code' => 'HT'],
            ['name' => 'Heard Island and McDonald Islands', 'official_state_name' => 'The Territory of Heard Island and McDonald Islands', 'code' => 'HM'],
            ['name' => 'Holy See (Vatican City State)', 'official_state_name' => 'The Holy See', 'code' => 'VA'],
            ['name' => 'Honduras', 'official_state_name' => 'The Republic of Honduras', 'code' => 'HN'],
            ['name' => 'Hong Kong', 'official_state_name' => 'The Hong Kong Special Administrative Region of China', 'code' => 'HK'],
            ['name' => 'Hungary', 'official_state_name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Iceland', 'official_state_name' => 'Iceland', 'code' => 'IS'],
            ['name' => 'India', 'official_state_name' => 'The Republic of India', 'code' => 'IN'],
            ['name' => 'Indonesia', 'official_state_name' => 'The Republic of Indonesia', 'code' => 'ID'],
            ['name' => 'Iran', 'official_state_name' => 'The Islamic Republic of Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'official_state_name' => 'The Republic of Iraq', 'code' => 'IQ'],
            ['name' => 'Ireland', 'official_state_name' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Isle of Man', 'official_state_name' => 'The Isle of Man', 'code' => 'IM'],
            ['name' => 'Israel', 'official_state_name' => 'The State of Israel', 'code' => 'IL'],
            ['name' => 'Italy', 'official_state_name' => 'The Italian Republic', 'code' => 'IT'],
            ['name' => 'Jamaica', 'official_state_name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Japan', 'official_state_name' => 'Japan', 'code' => 'JP'],
            ['name' => 'Jersey', 'official_state_name' => 'The Bailiwick of Jersey', 'code' => 'JE'],
            ['name' => 'Jordan', 'official_state_name' => 'The Hashemite Kingdom of Jordan', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'official_state_name' => 'The Republic of Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Kenya', 'official_state_name' => 'The Republic of Kenya', 'code' => 'KE'],
            ['name' => 'Kiribati', 'official_state_name' => 'The Republic of Kiribati', 'code' => 'KI'],
            ['name' => 'North Korea', 'official_state_name' => 'The Democratic People\'s Republic of Korea', 'code' => 'KP'],
            ['name' => 'South Korea', 'official_state_name' => 'The Republic of Korea', 'code' => 'KR'],
            ['name' => 'Kuwait', 'official_state_name' => 'The State of Kuwait', 'code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'official_state_name' => 'The Kyrgyz Republic', 'code' => 'KG'],
            ['name' => 'Lao People\'s Democratic Republic', 'official_state_name' => 'The Lao People\'s Democratic Republic', 'code' => 'LA'],
            ['name' => 'Latvia', 'official_state_name' => 'The Republic of Latvia', 'code' => 'LV'],
            ['name' => 'Lebanon', 'official_state_name' => 'The Lebanese Republic', 'code' => 'LB'],
            ['name' => 'Lesotho', 'official_state_name' => 'The Kingdom of Lesotho', 'code' => 'LS'],
            ['name' => 'Liberia', 'official_state_name' => 'The Republic of Liberia', 'code' => 'LR'],
            ['name' => 'Libya', 'official_state_name' => 'The State of Libya', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'official_state_name' => 'The Principality of Liechtenstein', 'code' => 'LI'],
            ['name' => 'Lithuania', 'official_state_name' => 'The Republic of Lithuania', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'official_state_name' => 'The Grand Duchy of Luxembourg', 'code' => 'LU'],
            ['name' => 'Macao', 'official_state_name' => 'The Macao Special Administrative Region of China', 'code' => 'MO'],
            ['name' => 'North Macedonia', 'official_state_name' => 'The Republic of North Macedonia', 'code' => 'MK'],
            ['name' => 'Madagascar', 'official_state_name' => 'The Republic of Madagascar', 'code' => 'MG'],
            ['name' => 'Malawi', 'official_state_name' => 'The Republic of Malawi', 'code' => 'MW'],
            ['name' => 'Malaysia', 'official_state_name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Maldives', 'official_state_name' => 'The Republic of Maldives', 'code' => 'MV'],
            ['name' => 'Mali', 'official_state_name' => 'The Republic of Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'official_state_name' => 'The Republic of Malta', 'code' => 'MT'],
            ['name' => 'Marshall Islands', 'official_state_name' => 'The Republic of the Marshall Islands', 'code' => 'MH'],
            ['name' => 'Martinique', 'official_state_name' => 'Martinique', 'code' => 'MQ'],
            ['name' => 'Mauritania', 'official_state_name' => 'The Islamic Republic of Mauritania', 'code' => 'MR'],
            ['name' => 'Mauritius', 'official_state_name' => 'The Republic of Mauritius', 'code' => 'MU'],
            ['name' => 'Mayotte', 'official_state_name' => 'The Department of Mayotte', 'code' => 'YT'],
            ['name' => 'Mexico', 'official_state_name' => 'The United Mexican States', 'code' => 'MX'],
            ['name' => 'Micronesia', 'official_state_name' => 'The Federated States of Micronesia', 'code' => 'FM'],
            ['name' => 'Moldova', 'official_state_name' => 'The Republic of Moldova', 'code' => 'MD'],
            ['name' => 'Monaco', 'official_state_name' => 'The Principality of Monaco', 'code' => 'MC'],
            ['name' => 'Mongolia', 'official_state_name' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Montenegro', 'official_state_name' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Montserrat', 'official_state_name' => 'Montserrat', 'code' => 'MS'],
            ['name' => 'Morocco', 'official_state_name' => 'The Kingdom of Morocco', 'code' => 'MA'],
            ['name' => 'Mozambique', 'official_state_name' => 'The Republic of Mozambique', 'code' => 'MZ'],
            ['name' => 'Myanmar', 'official_state_name' => 'The Republic of the Union of Myanmar', 'code' => 'MM'],
            ['name' => 'Namibia', 'official_state_name' => 'The Republic of Namibia', 'code' => 'NA'],
            ['name' => 'Nauru', 'official_state_name' => 'The Republic of Nauru', 'code' => 'NR'],
            ['name' => 'Nepal', 'official_state_name' => 'The Federal Democratic Republic of Nepal', 'code' => 'NP'],
            ['name' => 'Netherlands', 'official_state_name' => 'The Kingdom of the Netherlands', 'code' => 'NL'],
            ['name' => 'New Caledonia', 'official_state_name' => 'New Caledonia', 'code' => 'NC'],
            ['name' => 'New Zealand', 'official_state_name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'official_state_name' => 'The Republic of Nicaragua', 'code' => 'NI'],
            ['name' => 'Niger', 'official_state_name' => 'The Republic of the Niger', 'code' => 'NE'],
            ['name' => 'Nigeria', 'official_state_name' => 'The Federal Republic of Nigeria', 'code' => 'NG'],
            ['name' => 'Niue', 'official_state_name' => 'Niue', 'code' => 'NU'],
            ['name' => 'Norfolk Island', 'official_state_name' => 'The Territory of Norfolk Island', 'code' => 'NF'],
            ['name' => 'Northern Mariana Islands', 'official_state_name' => 'The Commonwealth of the Northern Mariana Islands', 'code' => 'MP'],
            ['name' => 'Norway', 'official_state_name' => 'The Kingdom of Norway', 'code' => 'NO'],
            ['name' => 'Oman', 'official_state_name' => 'The Sultanate of Oman', 'code' => 'OM'],
            ['name' => 'Pakistan', 'official_state_name' => 'The Islamic Republic of Pakistan', 'code' => 'PK'],
            ['name' => 'Palau', 'official_state_name' => 'The Republic of Palau', 'code' => 'PW'],
            ['name' => 'Palestine', 'official_state_name' => 'The State of Palestine', 'code' => 'PS'],
            ['name' => 'Panama', 'official_state_name' => 'The Republic of Panamá', 'code' => 'PA'],
            ['name' => 'Papua New Guinea', 'official_state_name' => 'The Independent State of Papua New Guinea', 'code' => 'PG'],
            ['name' => 'Paraguay', 'official_state_name' => 'The Republic of Paraguay', 'code' => 'PY'],
            ['name' => 'Peru', 'official_state_name' => 'The Republic of Perú', 'code' => 'PE'],
            ['name' => 'Philippines', 'official_state_name' => 'The Republic of the Philippines', 'code' => 'PH'],
            ['name' => 'Pitcairn', 'official_state_name' => 'The Pitcairn, Henderson, Ducie and Oeno Islands', 'code' => 'PN'],
            ['name' => 'Poland', 'official_state_name' => 'The Republic of Poland', 'code' => 'PL'],
            ['name' => 'Portugal', 'official_state_name' => 'The Portuguese Republic', 'code' => 'PT'],
            ['name' => 'Puerto Rico', 'official_state_name' => 'The Commonwealth of Puerto Rico', 'code' => 'PR'],
            ['name' => 'Qatar', 'official_state_name' => 'The State of Qatar', 'code' => 'QA'],
            ['name' => 'Réunion', 'official_state_name' => 'Réunion', 'code' => 'RE'],
            ['name' => 'Romania', 'official_state_name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Russia', 'official_state_name' => 'The Russian Federation', 'code' => 'RU'],
            ['name' => 'Rwanda', 'official_state_name' => 'The Republic of Rwanda', 'code' => 'RW'],
            ['name' => 'Saint Barthélemy', 'official_state_name' => 'The Collectivity of Saint-Barthélemy', 'code' => 'BL'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'official_state_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH'],
            ['name' => 'Saint Kitts and Nevis', 'official_state_name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['name' => 'Saint Lucia', 'official_state_name' => 'Saint Lucia', 'code' => 'LC'],
            ['name' => 'Saint Martin (French part)', 'official_state_name' => 'The Collectivity of Saint-Martin', 'code' => 'MF'],
            ['name' => 'Saint Pierre and Miquelon', 'official_state_name' => 'The Overseas Collectivity of Saint-Pierre and Miquelon', 'code' => 'PM'],
            ['name' => 'Saint Vincent and the Grenadines', 'official_state_name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['name' => 'Samoa', 'official_state_name' => 'The Independent State of Samoa', 'code' => 'WS'],
            ['name' => 'San Marino', 'official_state_name' => 'The Republic of San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'official_state_name' => 'The Democratic Republic of São Tomé and Príncipe', 'code' => 'ST'],
            ['name' => 'Saudi Arabia', 'official_state_name' => 'The Kingdom of Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Senegal', 'official_state_name' => 'The Republic of Senegal', 'code' => 'SN'],
            ['name' => 'Serbia', 'official_state_name' => 'The Republic of Serbia', 'code' => 'RS'],
            ['name' => 'Seychelles', 'official_state_name' => 'The Republic of Seychelles', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'official_state_name' => 'The Republic of Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapore', 'official_state_name' => 'The Republic of Singapore', 'code' => 'SG'],
            ['name' => 'Sint Maarten (Dutch part)', 'official_state_name' => 'Sint Maarten', 'code' => 'SX'],
            ['name' => 'Slovakia', 'official_state_name' => 'The Slovak Republic', 'code' => 'SK'],
            ['name' => 'Slovenia', 'official_state_name' => 'The Republic of Slovenia', 'code' => 'SI'],
            ['name' => 'Solomon Islands', 'official_state_name' => 'The Solomon Islands', 'code' => 'SB'],
            ['name' => 'Somalia', 'official_state_name' => 'The Federal Republic of Somalia', 'code' => 'SO'],
            ['name' => 'South Africa', 'official_state_name' => 'The Republic of South Africa', 'code' => 'ZA'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'official_state_name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['name' => 'South Sudan', 'official_state_name' => 'The Republic of South Sudan', 'code' => 'SS'],
            ['name' => 'Spain', 'official_state_name' => 'The Kingdom of Spain', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'official_state_name' => 'The Democratic Socialist Republic of Sri Lanka', 'code' => 'LK'],
            ['name' => 'Sudan', 'official_state_name' => 'The Republic of the Sudan', 'code' => 'SD'],
            ['name' => 'Suriname', 'official_state_name' => 'The Republic of Suriname', 'code' => 'SR'],
            ['name' => 'Svalbard and Jan Mayen', 'official_state_name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            ['name' => 'Sweden', 'official_state_name' => 'The Kingdom of Sweden', 'code' => 'SE'],
            ['name' => 'Switzerland', 'official_state_name' => 'The Swiss Confederation', 'code' => 'CH'],
            ['name' => 'Syrian Arab Republic', 'official_state_name' => 'The Syrian Arab Republic', 'code' => 'SY'],
            ['name' => 'Taiwan', 'official_state_name' => 'The Republic of China', 'code' => 'TW'],
            ['name' => 'Tajikistan', 'official_state_name' => 'The Republic of Tajikistan', 'code' => 'TJ'],
            ['name' => 'Tanzania', 'official_state_name' => 'The United Republic of Tanzania', 'code' => 'TZ'],
            ['name' => 'Thailand', 'official_state_name' => 'The Kingdom of Thailand', 'code' => 'TH'],
            ['name' => 'Timor-Leste', 'official_state_name' => 'The Democratic Republic of Timor-Leste', 'code' => 'TL'],
            ['name' => 'Togo', 'official_state_name' => 'The Togolese Republic', 'code' => 'TG'],
            ['name' => 'Tokelau', 'official_state_name' => 'Tokelau', 'code' => 'TK'],
            ['name' => 'Tonga', 'official_state_name' => 'The Kingdom of Tonga', 'code' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'official_state_name' => 'The Republic of Trinidad and Tobago', 'code' => 'TT'],
            ['name' => 'Tunisia', 'official_state_name' => 'The Republic of Tunisia', 'code' => 'TN'],
            ['name' => 'Turkiye', 'official_state_name' => 'The Republic of Türkiye', 'code' => 'TR'],
            ['name' => 'Turkmenistan', 'official_state_name' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Turks and Caicos Islands', 'official_state_name' => 'The Turks and Caicos Islands', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'official_state_name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'official_state_name' => 'The Republic of Uganda', 'code' => 'UG'],
            ['name' => 'Ukraine', 'official_state_name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'United Arab Emirates', 'official_state_name' => 'The United Arab Emirates', 'code' => 'AE'],
            ['name' => 'United Kingdom', 'official_state_name' => 'The United Kingdom of Great Britain and Northern Ireland', 'code' => 'GB'],
            ['name' => 'United States', 'official_state_name' => 'The United States of America', 'code' => 'US'],
            ['name' => 'United States Minor Outlying Islands', 'official_state_name' => 'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island', 'code' => 'UM'],
            ['name' => 'Uruguay', 'official_state_name' => 'The Oriental Republic of Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'official_state_name' => 'The Republic of Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'official_state_name' => 'The Republic of Vanuatu', 'code' => 'VU'],
            ['name' => 'Venezuela', 'official_state_name' => 'The Bolivarian Republic of Venezuela', 'code' => 'VE'],
            ['name' => 'Viet Nam', 'official_state_name' => 'The Socialist Republic of Viet Nam', 'code' => 'VN'],
            ['name' => 'Virgin Islands, British', 'official_state_name' => 'The Virgin Islands', 'code' => 'VG'],
            ['name' => 'Virgin Islands, U.S.', 'official_state_name' => 'The Virgin Islands of the United States', 'code' => 'VI'],
            ['name' => 'Wallis and Futuna', 'official_state_name' => 'The Territory of the Wallis and Futuna Islands', 'code' => 'WF'],
            ['name' => 'Western Sahara', 'official_state_name' => 'The Sahrawi Arab Democratic Republic', 'code' => 'EH'],
            ['name' => 'Yemen', 'official_state_name' => 'The Republic of Yemen', 'code' => 'YE'],
            ['name' => 'Zambia', 'official_state_name' => 'The Republic of Zambia', 'code' => 'ZM'],
            ['name' => 'Zimbabwe', 'official_state_name' => 'The Republic of Zimbabwe', 'code' => 'ZW']
        ];
    }
}
